---
- name: Create K8s config directory
  file:
    path: /home/ec2-user/k8s
    state: directory
    mode: '0755'
    owner: ec2-user
    group: ec2-user

- name: Template Kubernetes Deployment YAML
  template:
    src: deployment.yml.j2
    dest: /home/ec2-user/k8s/deployment.yml
    owner: ec2-user

- name: Copy Kubernetes Service YAML
  copy:
    src: service.yml
    dest: /home/ec2-user/k8s/service.yml
    owner: ec2-user

- name: Apply Deployment
  become_user: ec2-user
  shell: kubectl apply -f /home/ec2-user/k8s/deployment.yml

- name: Apply Service
  become_user: ec2-user
  shell: kubectl apply -f /home/ec2-user/k8s/service.yml

- name: Get Minikube IP
  become_user: ec2-user
  shell: minikube ip
  register: minikube_ip
  changed_when: false

- name: Forward EC2 port 80 to Minikube NodePort (30007)
  become: true
  shell: |
    iptables -t nat -C PREROUTING -p tcp --dport 80 -j DNAT --to-destination {{ minikube_ip.stdout }}:30007 || \
    iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination {{ minikube_ip.stdout }}:30007
    iptables -t nat -C POSTROUTING -j MASQUERADE || \
    iptables -t nat -A POSTROUTING -j MASQUERADE
  args:
    executable: /bin/bash

