apiVersion: v1
kind: Service
metadata:
  name: full-devops-service
spec:
  type: NodePort
  selector:
    app: full-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007

